### ISSUE TITLE
Webpack config rule

### ISSUE THREAD

**Issue by ogrotten** [mathieu-anderson/antd-theming-examples#5]
In your article that links to this repo, there's a direction: 

> Add a rule to the Webpack config to appropriately parse less files

I have no `/config` dir.

>Step 1: Create project

I assumed that to mean use create-react-app and then use this guide. Is there something else that I missed? Does the CRA need to be ejected?

**Comment by umair2288** [comment]
@ogrotten have you figured it out?

**Comment by ogrotten** [comment]
Nope. I moved on.
